### PR TITLE
Setting up the repo

### PR DESCRIPTION
**Pull request by sameedmohsin28**
In this pull request, I have
- Created react app.
- Installed React Redux, Redux Logger, React Router, Axios.
- Created `Header.js`, `Rockets.js`, `Missions.js`, and `MyProfile.js` page.
- Created a route in `App.js`.
- Used `<NavLink />` and `activeClassName`.
- Created `store.js`.
- Linked `store.js` with `index.js`.
- Created empty folders for slices.
- Created `api.js`.
- Added Linters.

### CODE REVIEW

**Comment by sameedmohsin28** [comment]
@Ali-0111 
Please carefully read the PR description to know exactly what work has been done till now in the repository. Please review the code. If everything is okay, please approve the changes and merge them. If you feel to change something, mention them in the review, and then you may change them yourself but please don't merge them before my review. I hope nothing's going to need to change.

Happy coding!

**Comment by sameedmohsin28** [comment]
@Ali-0111
Please carefully read the PR description to know exactly what work has been done till now in the repository. Please review the code. If everything is okay, please approve the changes and merge them. If you feel to change something, mention them in the review, and then you may change them yourself but please don't merge them before my review. I hope nothing's going to need to change.

Happy coding!

**Review by Ali-0111 — CHANGES_REQUESTED** [review]
Changes Required
@sameedmohsin28 
You did a lot of efforts for starting the project, so please find these suggestions we need:
1- in public directory, please remove all extra files create by default command `npm create-react-app`
2- we need to have a new folder next to src  for  all `.css ` files here. Right now, `.css` files are seprated and this way it is kindy of disarranged structure for files.

**Comment by sameedmohsin28** [comment]
> Changes Required @sameedmohsin28 You did a lot of efforts for starting the project, so please find these suggestions we need: 1- in public directory, please remove all extra files create by default command `npm create-react-app` 2- we need to have a new folder next to src for all `.css ` files here. Right now, `.css` files are seprated and this way it is kindy of disarranged structure for files.

Please review it now. I have made changes as requested.

**Review by Ali-0111 — APPROVED** [review]
@sameedmohsin28 
Lets to merge that, it is fine.

**Pull request merged**
